env:
  es6: true
  node: true

plugins:
  - wdio

extends:
  - 'airbnb-base'
  - plugin:wdio/recommended

globals:
  assert: true
  expect: true
  document: false


parserOptions:
  ecmaVersion: 8

root: true

rules:
  comma-dangle:
    - 'error'
    - arrays: 'always-multiline'
      objects: 'always-multiline'
      imports: 'never'
      exports: 'never'
      functions: 'ignore'
  class-methods-use-this: 'off' # Forces *everything*-static in classes with *any* state.
  global-require: 'off'
  import/no-extraneous-dependencies: 0
  indent:
    - 'error'
    - 4
    - SwitchCase: 1
  max-len:
    - 'error'
    - 120
    - ignorePattern: '\s*\/\^(.*)\$\/,$'
  new-cap:
    - 'error'
    - newIsCap: true
      capIsNewExceptions:
        - 'Given'
        - 'When'
        - 'Then'
  strict: 'off'
  no-console: 'off'

