version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node
      - image: blueimp/chromedriver
        ## init: true # required: https://github.com/blueimp/chromedriver/issues/5
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Create Download Directory
          command: mkdir ./tempDownload && chmod 777 -R ./tempDownload      
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines --frozen-lockfile --prod
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache
      - run: nc -vz localhost 4444 # Check chromedriver/chrome has started
      - run: yarn lint
      - run: yarn test:ci
      - store_test_results:
          path: ~/app/build
      - store_artifacts:
          path: ~/app/build
      - slack/status:
          fail_only: true
          only_for_branches: master
          webhook: ${SLACK_WEBHOOK_ERROR}
      - slack/status:
          fail_only: false
          only_for_branches: master
          webhook: ${SLACK_WEBHOOK_SUCCESS}

workflows:
  version: 2
  commit:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test

orbs:
  slack: circleci/slack@3.4.1
